force-app/main/default/objects/CSV_Export_File__mdt/CSV_Export_File__mdt.object-meta.xml
<CustomObject>
    <description>Use this to define the CSV Export File</description>
    <label>CSV Export File</label>
    <pluralLabel>CSV Export Files</pluralLabel>
</CustomObject>

force-app/main/default/objects/CSV_Export_File__mdt/fields/CSV_Header__c.field-meta.xml
<CustomField>
    <fullName>CSV_Header__c</fullName>
    <inlineHelpText>Use this to enter the comma separated values for the export</inlineHelpText>
    <label>CSV Header</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CSV_Export_File__mdt/fields/FileName__c.field-meta.xml
<CustomField>
    <fullName>FileName__c</fullName>
    <inlineHelpText>Enter the name of the file as you want it saved - do not include the extension for the file this is automatically appended to the created file.</inlineHelpText>
    <label>FileName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CSV_Export_File__mdt/fields/Use_Versioning__c.field-meta.xml
<CustomField>
    <fullName>Use_Versioning__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check this box to generate version of files if left a unticked multiple files will appear in the related files list.</inlineHelpText>
    <label>Use Versioning</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CSV_Export_File_Line__mdt/CSV_Export_File_Line__mdt.object-meta.xml
<CustomObject>
    <description>Use this to specify the lines item mapping for the export</description>
    <label>CSV Export File Line</label>
    <pluralLabel>CSV Export File Lines</pluralLabel>
</CustomObject>

force-app/main/default/classes/CSVExport_ExportBatchable.cls
/**
 * @description    Batch class to process finance batch and generate csv file
 * @author          philip@hyphen8.com
 * @date            12/02/2021
 * @group           Helper
*/
public  class CSVExport_ExportBatchable implements Database.Batchable<SObject> , Database.stateful {

    private List<SObject> exportRecords = new List<SObject>();
    private Map<String, List<String>> lineFieldMappings;
    private List<CSV_Export_File_Line__mdt> listOfLineMappings;
    private ID contentDocumentID;
    private CSV_Export_File__mdt exportMappingRecord;
    string recordId;
    private String csv;
    private string fieldSetQuery;
    private String soqlQuery;


    public CSVExport_ExportBatchable(string rid,
                                     CSV_Export_File__mdt emr) {

        this.recordId = rid;
        this.exportMappingRecord = emr;

    }

    public Database.QueryLocator start(Database.BatchableContext BC){


        listOfLineMappings = CSVExport_ExportHelper.getMappingsLines(exportMappingRecord.Id);
        lineFieldMappings = CSVExport_ExportHelper.getLineFieldMapping(listOfLineMappings);
        fieldSetQuery = CSVExport_ExportHelper.getSOQLFieldQuery(listOfLineMappings);
        soqlQuery = CSVExport_ExportHelper.getRecordsToProcess(exportMappingRecord, fieldSetQuery, recordId);
        csv = exportMappingRecord.CSV_Header__c + '\n';

        return Database.getQueryLocator(soqlQuery);
    }

    public void execute(Database.BatchableContext BC,List<SObject> listOfRecords){

        for(SObject record:listOfRecords){
            string recordlines = CSVExport_ExportHelper.getLineValues(record, lineFieldMappings);
            csv = csv + recordlines;
        }


    }

    public void finish(Database.BatchableContext BC){

        contentDocumentID = CSVExport_ExportHelper.getExistingContentDocumentID(recordId, exportMappingRecord.FileName__c);
        CSVExport_ExportHelper.generateContentFile(csv, recordId, contentDocumentID, exportMappingRecord.Use_Versioning__c, exportMappingRecord.FileName__c);

    }

}