force-app/main/default/objects/CSV_Import_Mapping__mdt/CSV_Import_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>This helps define what records will be imported</description>
    <label>CSV Import Mapping</label>
    <pluralLabel>CSV Import Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/CSV_Import_Mapping__mdt/fields/Mapping_Field__c.field-meta.xml
<CustomField>
    <fullName>Mapping_Field__c</fullName>
    <inlineHelpText>Select the field on the import object that you want to link this csv export to</inlineHelpText>
    <label>Mapping Field</label>
    <metadataRelationshipControllingField>CSV_Import_Mapping__mdt.Import_Object__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>CSV_Import_Mapping_Field</relationshipLabel>
    <relationshipName>CSV_Import_Mapping_Field</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/classes/CSVExport_ImportBatchable.cls
/**
 * @description    Batch class to process funding payments and add them to finance batch
 * @author          philip@hyphen8.com
 * @date            12/02/2021
 * @group           Helper
*/
public  class CSVExport_ImportBatchable implements Database.Batchable<SObject> , Database.stateful {


    CSV_Import_Mapping__mdt  importMappingRecord;
    String soqlQuery;
    String recordId;

    public CSVExport_ImportBatchable(string rid,
                                     CSV_Import_Mapping__mdt cim,
                                     String soql) {

        this.recordId = rid;
        this.importMappingRecord = cim;
        this.soqlQuery = soql;

    }

    public Database.QueryLocator start(Database.BatchableContext BC){


        return Database.getQueryLocator(soqlQuery);
    }

    public void execute(Database.BatchableContext BC,List<SObject> listOfRecords){

        List<SObject> updateList = new List<SObject>();

        for(SObject record:listOfRecords){
            string mappingfield = importMappingRecord.Mapping_Field__r.QualifiedApiName;
            record.put(mappingfield, recordId);
            updateList.add(record);
        }

        // perform update
        Database.update(updateList);


    }

    public void finish(Database.BatchableContext BC){

    }

}